name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install XFCE4 and xrdp
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies xrdp
        echo xfce4-session > ~/.xsession

    - name: Configure xrdp
      run: |
        sudo cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak
        sudo sed -i 's/3389/3390/' /etc/xrdp/xrdp.ini
        sudo sed -i 's/max_bpp=32/max_bpp=24/' /etc/xrdp/xrdp.ini
        sudo sed -i 's/xserverbpp=24/xserverbpp=16/' /etc/xrdp/xrdp.ini
        echo "xfce4-session" | sudo tee /etc/skel/.xsession
        sudo systemctl restart xrdp

    - name: Setup user for RDP
      run: |
        sudo usermod -a -G sudo,adm runneradmin
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Start ngrok Tunnel
      run: |
        ./ngrok tcp 3390 --region=us
