name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install LXDE and VNC server
      run: |
        sudo apt-get update
        sudo apt-get install -y lxde-core lxterminal tightvncserver

    - name: Set VNC password
      run: |
        mkdir -p ~/.vnc
        echo -e "yourVNCpasswordnyourVNCpassword" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Set up VNC server to use LXDE
      run: |
        echo "#!/bin/bash
        xrdb $HOME/.Xresources
        startlxde &" > ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup

    - name: Start VNC server
      run: |
        vncserver -kill :1 || true
        vncserver :1 -geometry 1280x800 -depth 24

    - name: Download and extract ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
        unzip -o ngrok.zip

    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok Tunnel for VNC
      run: |
        ./ngrok tcp 5901 
