name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install and configure xrdp for RDP access
      run: |
        sudo apt install xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389
        sudo ufw reload
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo adduser xrdp ssl-cert
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd
        sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config

    - name: Create ngrok Tunnel
      run: ./ngrok tcp 3389
